name: Deploy PokeAPI to EC2

on:
  push:
    branches:
      - master  # Trigger when pushing to the main branch

jobs:
  create-ec2-deploy:
    name: Create EC2 and Deploy Flask App
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Provide authentication for GitHub CLI

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-west-2

      - name: Check if Key Pair exists
        id: keypair-check
        run: |
          KEY_PAIR_NAME="${{ secrets.KEY_PAIR_NAME }}"
          EXISTING_KEY=$(aws ec2 describe-key-pairs --key-names $KEY_PAIR_NAME --query 'KeyPairs[0].KeyName' --output text || echo "")
          if [ -z "$EXISTING_KEY" ]; then
              echo "Key Pair does not exist. Consider creating one."
              exit 1  # Fail the job if the key pair does not exist
          else
              echo "Using existing key pair: ${EXISTING_KEY}"
          fi

      - name: Check if Security Group exists
        id: sg-check
        run: |
          SECURITY_GROUP_NAME="PokeAPI-SG"
          EXISTING_SG=$(aws ec2 describe-security-groups --group-names $SECURITY_GROUP_NAME --query 'SecurityGroups[0].GroupId' --output text || echo "")
          if [ -z "$EXISTING_SG" ]; then
            SG_ID=$(aws ec2 create-security-group --group-name $SECURITY_GROUP_NAME --description "Security group for Flask app" --output text)
            echo "SG_ID=${SG_ID}" >> $GITHUB_ENV
            aws ec2 authorize-security-group-ingress --group-id $SG_ID --protocol tcp --port 22 --cidr 0.0.0.0/0  # Allow SSH
            aws ec2 authorize-security-group-ingress --group-id $SG_ID --protocol tcp --port 80 --cidr 0.0.0.0/0  # Allow HTTP
            aws ec2 authorize-security-group-ingress --group-id $SG_ID --protocol tcp --port 5000 --cidr 0.0.0.0/0  # Allow HTTP on port 5000
          else
            echo "SG_ID=${EXISTING_SG}" >> $GITHUB_ENV
          fi

      - name: Check if EC2 instance exists
        id: ec2-check
        run: |
          # INSTANCE_ID=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=PokeAPI" --query "Reservations[*].Instances[*].InstanceId" --output text)
          INSTANCE_ID=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=PokeAPI" "Name=instance-state-name,Values=pending,running" --query "Reservations[*].Instances[*].InstanceId" --output text)
          if [ -n "$INSTANCE_ID" ]; then
            echo "INSTANCE_ID=${INSTANCE_ID}" >> $GITHUB_ENV
          fi
          
      - name: Find Amazon Linux 2 AMI ID
        id: ami-find
        run: |
          AMI_ID=$(aws ec2 describe-images --owners amazon --filters "Name=name,Values=amzn2-ami-hvm-*-x86_64-gp2" "Name=architecture,Values=x86_64" --query "Images[?contains(Name, 'amzn2-ami-hvm-')].[ImageId]" --output text | head -n 1)
          echo "AMI_ID=${AMI_ID}" >> $GITHUB_ENV
          
      - name: Create EC2 Instance if Not Exists
        if: env.INSTANCE_ID == ''
        id: ec2-create
        run: |
          INSTANCE_ID=$(aws ec2 run-instances \
            --image-id ${{ env.AMI_ID }} \
            --instance-type t2.micro \
            --key-name ${{ secrets.KEY_PAIR_NAME }} \
            --security-group-ids ${{ env.SG_ID }} \
            --tag-specifications 'ResourceType=instance,Tags=[{Key=Name,Value=PokeAPI}]' \
            --query "Instances[0].InstanceId" \
            --output text)
          echo "INSTANCE_ID=${INSTANCE_ID}" >> $GITHUB_ENV
      - name: Wait for EC2 instance to be running
        run: |
          aws ec2 wait instance-running --instance-ids ${{ env.INSTANCE_ID }}
          
      - name: Get EC2 public DNS
        id: ec2-dns
        run: |
          PUBLIC_DNS=$(aws ec2 describe-instances --instance-ids ${{ env.INSTANCE_ID }} --query "Reservations[*].Instances[*].PublicDnsName" --output text)
          echo "PUBLIC_DNS=${PUBLIC_DNS}" >> $GITHUB_ENV
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Add EC2 to known_hosts
        run: ssh-keyscan -H ${{ env.PUBLIC_DNS }} >> ~/.ssh/known_hosts

      - name: Run setup script for Flask app
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ env.PUBLIC_DNS }} << 'EOF'
          # set -e  # Exit immediately if a command exits with a non-zero status

          # Update the system and install required packages
          sudo yum update -y && sudo yum upgrade -y || { echo "Failed to update system"; exit 1; }
          sudo amazon-linux-extras install nginx1 || { echo "Failed to install Nginx"; exit 1; }
          sudo yum install python3 python3-devel git nginx -y || { echo "Failed to install required packages"; exit 1; }
          
          sudo yum install python3-pip -y
      
          # # Install necessary Python packages
          # pip3 install requests urllib3==1.26.16 flask gunicorn || { echo "Failed to install Flask and Gunicorn"; exit 1; }

         
          # Modify nginx.conf if not set
          if ! grep -q "server_names_hash_bucket_size 128;" /etc/nginx/nginx.conf; then
            sudo sed -i '/http {/a \    server_names_hash_bucket_size 128;' /etc/nginx/nginx.conf
          fi
          
          # Create application directory
          APP_DIR="/home/ec2-user/PokeAPI"
          if [ ! -d "$APP_DIR" ]; then
            git clone https://github.com/ChenBello/pokeAPI.git "$APP_DIR" || { echo "Failed to clone repository"; exit 1; }
          else
            cd "$APP_DIR" && git pull origin master || { echo "Failed to pull latest changes"; exit 1; }
          fi
          
          # # Create virtual environment
          # cd "$APP_DIR"
          # python3 -m venv venv
          # source venv/bin/activate

          # Update pip to the newest version
          pip install --upgrade pip
          # (/home/ec2-user/PokeAPI/myenv/bin/python3 -m pip install --upgrade pip)

          # Install required package
          pip3 install requests urllib3==1.26.16 flask gunicorn || { echo "Failed to install Flask and Gunicorn"; exit 1; }

          # Install required packages from requirements.txt
          # pip install -r requirements.txt || { echo "Failed to install requirements"; exit 1; }

          # # Create start script
          # echo '#!/usr/bin/env python3' > $APP_DIR/start_script.sh
          # echo 'python3 $APP_DIR/apiHandling.py' >> $APP_DIR/start_script.sh
          # chmod +x $APP_DIR/start_script.sh

          # # Add start script to /etc/rc.local
          # if ! grep -q "$APP_DIR/start_script.sh" /etc/rc.local; then
          #   sudo sed -i "/exit 0/i $APP_DIR/start_script.sh &" /etc/rc.local
          # fi

          # Change directory to flask_app
          cd "$APP_DIR/flask_app"
          
          # sudo iptables -A INPUT -p tcp --dport 80 -j ACCEPT
          # sudo iptables -A INPUT -p tcp --dport 5000 -j ACCEPT
          # sudo service iptables save
          # sudo systemctl enable iptables

          sudo groupadd nginx
          sudo usermod -aG nginx ec2-user
          newgrp nginx

          # Create systemd service
          sudo tee /etc/systemd/system/PokeAPI.service > /dev/null <<EOL
          [Unit]
          Description=PokeAPI service
          After=network.target
          
          [Service]
          User=ec2-user
          Group=nginx
          WorkingDirectory=$APP_DIR/flask_app
          ExecStart=/home/ec2-user/.local/bin/gunicorn --workers 3 --bind unix:/home/ec2-user/PokeAPI/PokeAPI.sock app:app
          Restart=always
          
          [Install]
          WantedBy=multi-user.target
          EOL

          sudo chown ec2-user:nginx /home/ec2-user/PokeAPI/PokeAPI.sock
          sudo chmod 660 /home/ec2-user/PokeAPI/PokeAPI.sock


          sudo systemctl daemon-reload
          sudo systemctl start PokeAPI || { echo "Failed to start PokeAPI service"; exit 1; }
          sudo systemctl enable PokeAPI

          # Configure Nginx
          sudo tee /etc/nginx/conf.d/PokeAPI.conf > /dev/null <<EOL
          server {
              listen 80;
              server_name ${{ env.PUBLIC_DNS }};
              location / {
                  proxy_pass http://unix:$APP_DIR/PokeAPI.sock;
                  proxy_set_header Host \$host;
                  proxy_set_header X-Real-IP \$remote_addr;
                  proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto \$scheme;
              }
          }
          EOL

          # Check Nginx configuration
          sudo nginx -t || { echo "Nginx configuration failed"; exit 1; }
          sudo systemctl restart nginx || { echo "Failed to restart Nginx"; exit 1; }
          sudo systemctl enable nginx  
          sudo systemctl status nginx
          
          # # Check Nginx configuration and restart
          # sudo nginx -t && sudo systemctl restart nginx

          # Update .bashrc
          BASHRC="$HOME/.bashrc"
          
          # # Check if alias already exists, if not, add it
          # if ! grep -q 'alias start_pokemon_app="python3 /home/ec2-user/PokeAPI/apiHandling.py"' "$BASHRC"; then
          #     echo 'alias start_pokemon_app="python3 /home/ec2-user/PokeAPI/apiHandling.py"' >> "$BASHRC"
          # fi
          
          # # Check if welcome message already exists, if not, add it
          # if ! grep -q "Welcome to the Pokémon app! Type 'start_pokemon_app' to start drawing Pokémon." "$BASHRC"; then
          #     echo "Welcome to the Pokémon app! Type 'start_pokemon_app' to start drawing Pokémon." >> "$BASHRC"
          # fi
          
          # Check if apiHandling.py is already executed, if not, add it
          if ! grep -q "python3 /home/ec2-user/PokeAPI/apiHandling.py" "$BASHRC"; then
              echo "python3 /home/ec2-user/PokeAPI/apiHandling.py" >> "$BASHRC"
          fi

          EOF

      # - name: Create start script
      #   run: |
      #     echo '#!/usr/bin/env python3' > /home/ec2-user/PokeAPI/start_script.sh
      #     echo 'python3 /home/ec2-user/PokeAPI/apiHandling.py' >> /home/ec2-user/PokeAPI/start_script.sh
      #     chmod +x /home/ec2-user/PokeAPI/start_script.sh

      # - name: Add start script to /etc/rc.local
      #   run: |
      #     if ! grep -q "/home/ec2-user/PokeAPI/start_script.sh" /etc/rc.local; then
      #       sudo sed -i "/exit 0/i /home/ec2-user/PokeAPI/start_script.sh &" /etc/rc.local
      #     fi
      
      - name: Wait for the app to start
        run: sleep 15  # Wait for 15 seconds

      
      - name: Test if the app is running
        run: |
          APP_URL="http://${{ env.PUBLIC_DNS }}"
          RESPONSE=$(curl --write-out "%{http_code}\n" --silent --output /dev/null $APP_URL)
          if [ "$RESPONSE" -eq 200 ]; then
            echo "PokeAPI is running successfully! Response code: $RESPONSE"
          else
            echo "Failed to reach PokeAPI. Response code: $RESPONSE"
            exit 1  # Fail the job if the app is not running
          fi
      # - name: Test if the app is running
      #   run: |
      #     curl -I http://${{ env.PUBLIC_DNS }} | grep "200 OK" || echo "Failed to connect to the app"
